name: AWS EC2 CI/CD React with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, window-2016 ]
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
      - run: ls -al